export const TASK_SCHEMA = 'TASK_SCHEMA';
export const USER_SCHEMA = 'USER_SCHEMA';
export const NEWS_SCHEMA = 'NEWS_SCHEMA';
export const CREATE_TASK_SCHEMA = 'CREATE_TASK_SCHEMA';
export const TASK_CONTROLL_JURNAL_SCHEMA = 'TASK_CONTROLL_JURNAL_SCHEMA';
export const WIKI_NODE_TREE = 'WIKI_NODE_TREE';
