export const TASK_SCHEMA = "TASK_SCHEMA";
export const USER_SCHEMA = "USER_SCHEMA";
export const NEWS_SCHEMA = "NEWS_SCHEMA";
export const TASK_CONTROLL_JURNAL_SCHEMA = "TASK_CONTROLL_JURNAL_SCHEMA";
