export const SET_ACTIVE_CHAT_TOKEN = "SET_ACTIVE_CHAT_TOKEN";
export const SET_SOCKET_CONNECTION = "SET_SOCKET_CONNECTION";
export const LOAD_CHATS_LIST = "LOAD_CHATS_LIST";
export const INVALID_LOAD_SOCKET = "INVALID_LOAD_SOCKET";
export const ADD_CHAT_MSG = "ADD_CHAT_MSG";
export const UPDATE_ENTITY_SOCKET = "UPDATE_ENTITY_SOCKET";